version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
        - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    container_name: django_docker
    build: .
    command:  bash -c "python /usr/src/app/manage.py migrate --noinput &&
              python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_USER_PASSWORD=postgres
    depends_on:
      - db
volumes:
  postgres: