# Generated by Django 3.2.9 on 2022-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=150, verbose_name='Email пользователя')),
            ],
        ),
    ]
